### PR TITLE
Bids 3075/validator subset modal v2 5

### PR DESCRIPTION
**Pull request by MauserBitfly**
This PR:

- refactors the validator subset modal according to the 2.5 layouts
- removes dupplicate value in the summary details on mobile 

Note to the reviewer: Data is currently mocked in the backend

### CODE REVIEW

**Comment by thib-wien** [comment]
The `i` and the `↗` are beautifully aligned but they seem to belong to column `Efficiency`. Same with the other occurences in other columns.
Screenshot from 2024-06-26 14-11-52

Figma look more messy but less confusing:
Screenshot from 2024-06-26 14-11-34

**Comment by thib-wien** [comment]
image
Maybe `\<` and `\>` would solve it ?

**Review by thib-wien — COMMENTED** [review]
👍🏻

**Comment by MauserBitfly** [comment]
> image Maybe `\<` and `\>` would solve it ?

removed the <> - stuff as it's more readable for the user anyway.

**Comment by MauserBitfly** [comment]
> The `i` and the `↗` are beautifully aligned but they seem to belong to column `Efficiency`. Same with the other occurences in other columns. Screenshot from 2024-06-26 14-11-52
> 
> Figma look more messy but less confusing: Screenshot from 2024-06-26 14-11-34

removed the space between

**Pull request merged**
